/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccountManagement: typeof import('./src/components/AccountManagement.vue')['default']
    BlueOpening: typeof import('./src/components/BlueOpening.vue')['default']
    BurnPage2: typeof import('./src/components/BurnPage2.vue')['default']
    CodePage: typeof import('./src/components/CodePage.vue')['default']
    Coding: typeof import('./src/components/Coding.vue')['default']
    CompileOutput: typeof import('./src/components/CompileOutput.vue')['default']
    DeviceCard: typeof import('./src/components/DeviceCard.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckTag: typeof import('element-plus/es')['ElCheckTag']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    GetDevice: typeof import('./src/components/GetDevice.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    LampControl: typeof import('./src/components/LampControl.vue')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SmartClass: typeof import('./src/components/SmartClass.vue')['default']
    SmartFarm: typeof import('./src/components/SmartFarm.vue')['default']
    SmartOpening: typeof import('./src/components/SmartOpening.vue')['default']
    SmartStorage: typeof import('./src/components/SmartStorage.vue')['default']
    Splitter: typeof import('./src/components/Splitter.vue')['default']
    Title: typeof import('./src/components/Title.vue')['default']
  }
}
