/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BlueOpening: typeof import('./src/components/BlueOpening.vue')['default']
    CodePage: typeof import('./src/components/CodePage.vue')['default']
    Coding: typeof import('./src/components/Coding.vue')['default']
    CompileOutput: typeof import('./src/components/CompileOutput.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    GetDevice: typeof import('./src/components/GetDevice.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    HomeHeader: typeof import('./src/components/home/HomeHeader.vue')['default']
    HomeMain: typeof import('./src/components/home/HomeMain.vue')['default']
    LampControl: typeof import('./src/components/LampControl.vue')['default']
    Register: typeof import('./src/components/Register.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SmartClass: typeof import('./src/components/SmartClass.vue')['default']
    SmartFarm: typeof import('./src/components/SmartFarm.vue')['default']
    SmartOpening: typeof import('./src/components/SmartOpening.vue')['default']
    SmartStorage: typeof import('./src/components/SmartStorage.vue')['default']
    Splitter: typeof import('./src/components/Splitter.vue')['default']
    UpdateUser: typeof import('./src/components/UpdateUser.vue')['default']
    User: typeof import('./src/components/User.vue')['default']
  }
}
